#pragma once

#include <stdint.h>

// Generated by fontexport.py plugin for Gimp

// Each character is represented by 16 rows of integers representing the bit mask for each rows.
uint32_t ata_mono16_data[95][16];

#define CREATE_ATA_MONO16() {  \
    init_canvas_font("ata_mono16", 8, 16, ' ', '~', (uint32_t*)ata_mono16_data)  \
}
