#pragma once

#include <stdint.h>
#include "ssd-1306-i2c.h"

// Generated by fontexport.py plugin for Gimp

// Each character is represented by 12 rows of integers representing the bit mask for each rows.
uint32_t ata_monobold12_data[95][12];

#define CREATE_ATA_MONOBOLD12() ({  \
    canvas_font_handle __ret = init_canvas_font("ata_monobold12", 6, 12, ' ', '~', (uint32_t*)ata_monobold12_data);  \
    (__ret);  \
})
