#pragma once

#include <stdint.h>
#include "ssd-1306-i2c.h"

// Generated by fontexport.py plugin for Gimp

// Each character is represented by 16 rows of integers representing the bit mask for each rows.
uint32_t ata_monobold16_data[95][16];

#define CREATE_ATA_MONOBOLD16() ({  \
    canvas_font_handle __ret = init_canvas_font("ata_monobold16", 8, 16, ' ', '~', (uint32_t*)ata_monobold16_data);  \
    (__ret);  \
})
